"""Controlled demonstration catalogue. Replace only with reviewed official data."""

SERVICES = (
    {
        "id": "merton-housing-repairs",
        "name": "Housing repairs",
        "description": "Report a repair if Merton Council is responsible for your home.",
        "url": "https://www.merton.gov.uk/council-tax-benefits-and-housing/housing/housing-repairs",
        "reviewed_on": "2026-08-27",
        "terms": ("leak", "leaking", "toilet", "repair", "council home", "housing repair"),
    },
    {
        "id": "merton-benefits-advice",
        "name": "Benefits advice",
        "description": "Find council information about benefits and financial support.",
        "url": "https://www.merton.gov.uk/council-tax-benefits-and-housing/benefits",
        "reviewed_on": "2026-08-27",
        "terms": ("benefit", "benefits", "universal credit", "low income", "financial support"),
    },
    {
        "id": "merton-street-cleaning",
        "name": "Litter and street cleaning",
        "description": "Report litter, fly-tipping or a street-cleaning problem.",
        "url": "https://www.merton.gov.uk/rubbish-and-recycling/litter-fly-tipping-and-street-cleaning",
        "reviewed_on": "2026-08-27",
        "terms": ("litter", "fly tipping", "fly-tipping", "street cleaning", "rubbish street"),
    },
    {
        "id": "merton-bulky-waste",
        "name": "Bulky waste collection",
        "description": "Book or manage a council collection for furniture, fridges and other bulky household items.",
        "url": "https://www.merton.gov.uk/rubbish-and-recycling/bulky-hazardous-and-clinical-waste/furniture-fridges-and-bulky-items",
        "reviewed_on": "2026-09-03",
        "terms": ("bulky waste", "bulky collection", "sofa collection", "fridge collection", "mattress collection"),
    },
    {
        "id": "merton-resident-parking-permit",
        "name": "Resident parking permits",
        "description": "Check eligibility and apply for or renew a resident parking permit in Merton.",
        "url": "https://www.merton.gov.uk/streets-parking-transport/parking/permits/resident",
        "reviewed_on": "2026-09-03",
        "terms": ("resident parking permit", "parking permit", "cpz permit", "resident permit"),
    },
    {
        "id": "merton-blue-badge",
        "name": "Blue Badge",
        "description": "Find Merton guidance for applying for or renewing a Blue Badge.",
        "url": "https://www.merton.gov.uk/streets-parking-transport/parking/bluebadge",
        "reviewed_on": "2026-09-03",
        "terms": ("blue badge", "disabled parking badge", "disability parking"),
    },
    {
        "id": "merton-council-tax-payment",
        "name": "Pay Council Tax",
        "description": "Find official options for paying Merton Council Tax or checking payment information.",
        "url": "https://www.merton.gov.uk/council-tax-benefits-and-housing/council-tax/paying-your-council-tax",
        "reviewed_on": "2026-09-03",
        "terms": ("pay council tax", "council tax payment", "council tax direct debit", "council tax balance"),
    },
    {
        "id": "merton-noise-nuisance",
        "name": "Noise and nuisance complaints",
        "description": "Use Merton Council guidance to report serious, ongoing noise or other nuisance problems.",
        "url": "https://www.merton.gov.uk/communities-and-neighbourhoods/noise-nuisance/report-nuisance/complaint",
        "reviewed_on": "2026-09-03",
        "terms": ("noise complaint", "noise nuisance", "report noise", "loud music complaint", "barking dog noise"),
    },
    {
        "id": "merton-school-admissions",
        "name": "School admissions",
        "description": "Find official Merton information for applying for a school place or transfer.",
        "url": "https://www.merton.gov.uk/education-and-learning/schools/admissions",
        "reviewed_on": "2026-09-03",
        "terms": ("school place", "school admission", "school admissions", "primary school application", "secondary school application", "school transfer"),
    },
    {
        "id": "merton-road-pavement",
        "name": "Road and pavement problems",
        "description": "Report potholes, damaged pavements and other road or pavement defects in Merton.",
        "url": "https://www.merton.gov.uk/streets-parking-transport/streets-and-pavements/potholes",
        "reviewed_on": "2026-09-03",
        "terms": ("pothole", "road damage", "damaged pavement", "pavement damage", "road surface problem"),
    },
    {
        "id": "merton-contact",
        "name": "Contact Merton Council",
        "description": "Use the council contact directory when no specific service can be identified.",
        "url": "https://www.merton.gov.uk/council-and-local-democracy/contact-us",
        "reviewed_on": "2026-08-27",
        "terms": ("contact council", "council contact", "speak to council"),
    },
)
